groups:
  - name: cpu_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 * (1 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))) > 75
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage Alert"
          description: "Instance {{ $labels.instance }} has high CPU usage ({{ humanize $value }}%)"
